import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Leaf, 
  Zap, 
  Droplets, 
  Trash2, 
  TrendingDown, 
  Cpu, 
  Building2, 
  FileDown, 
  ChevronRight, 
  ArrowRight,
  Shield,
  Globe,
  BarChart3,
  X
} from 'lucide-react';
import { BuildingType } from '../types';
import { cn } from '../lib/utils';

interface LandingPageProps {
  onLaunch: (institutionName: string, buildingType: BuildingType) => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onLaunch }) => {
  const [showModal, setShowModal] = useState(false);
  const [institutionName, setInstitutionName] = useState('');
  const [selectedType, setSelectedType] = useState<BuildingType>('Campus');

  useEffect(() => {
    if (showModal) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [showModal]);

  const features = [
    { title: 'Energy Prediction', icon: Zap, desc: 'Neural forecasting of energy demand and peak load shifting.', color: 'text-lime-400', border: 'hover:border-lime-500/30' },
    { title: 'Carbon Estimation', icon: Leaf, desc: 'Real-time carbon footprint tracking and offset simulation.', color: 'text-emerald-400', border: 'hover:border-emerald-500/30' },
    { title: 'Water Analytics', icon: Droplets, desc: 'Advanced consumption monitoring and recovery protocols.', color: 'text-cyan-400', border: 'hover:border-cyan-500/30' },
    { title: 'Waste Optimization', icon: Trash2, desc: 'Smart diversion rates and bio-waste management strategies.', color: 'text-rose-400', border: 'hover:border-rose-500/30' },
    { title: 'Sustainability Score', icon: BarChart3, desc: 'Comprehensive rating of your facility\'s environmental impact.', color: 'text-amber-400', border: 'hover:border-amber-500/30' },
    { title: 'AI Recommendations', icon: Sparkles, desc: 'Personalized, actionable protocols generated by Gemini AI.', color: 'text-violet-400', border: 'hover:border-violet-500/30' },
    { title: 'Report Generation', icon: FileDown, desc: 'Downloadable sustainability reports for stakeholder review.', color: 'text-blue-400', border: 'hover:border-blue-500/30' },
  ];

  const steps = [
    { number: '01', title: 'Data Integration', desc: 'Upload CSV or use existing telemetry streams.' },
    { number: '02', title: 'Neural Analysis', desc: 'AI predicts trends and identifies inefficiencies.' },
    { number: '03', title: 'Optimization', desc: 'Receive tailored protocols for resource reduction.' },
    { number: '04', title: 'Reporting', desc: 'Export detailed impact reports in seconds.' },
  ];

  const targets = [
    { type: 'Universities', icon: Building2 },
    { type: 'Hospitals', icon: Shield },
    { type: 'Offices', icon: Globe },
    { type: 'Residential Complexes', icon: Building2 },
  ];

  return (
    <div className="min-h-screen bg-eco-gradient text-white font-sans selection:bg-emerald-500/30 overflow-x-hidden relative">
      {/* Background Atmosphere & Architectural Silhouette */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        {/* 3D Architectural Silhouette (Simulated with low-poly monochrome image) */}
        <div className="absolute inset-0 z-0 opacity-[0.04] grayscale blur-[2px]">
          <img 
            src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=2070" 
            alt="City Silhouette" 
            className="w-full h-full object-cover object-bottom"
            referrerPolicy="no-referrer"
          />
        </div>

        {/* Eco Grid Structure Overlay */}
        <div className="absolute inset-0 z-0 opacity-[0.03]" 
             style={{ 
               backgroundImage: `linear-gradient(to right, #10b981 1px, transparent 1px), linear-gradient(to bottom, #10b981 1px, transparent 1px)`,
               backgroundSize: '60px 60px'
             }} 
        />

        {/* Depth Fog (Bottom to Top) */}
        <div className="absolute inset-0 z-0 bg-gradient-to-t from-[#020d0a] via-[#020d0a]/40 to-transparent" />

        {/* Atmospheric Glows */}
        <div className="absolute top-[-20%] left-[-10%] w-[70%] h-[70%] bg-emerald-900/20 blur-[120px] rounded-full animate-pulse-glow" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[70%] h-[70%] bg-teal-900/20 blur-[120px] rounded-full animate-pulse-glow" style={{ animationDelay: '-2s' }} />
        <div className="absolute top-[20%] right-[10%] w-[40%] h-[40%] bg-emerald-500/[0.03] blur-[100px] rounded-full" />
      </div>

      {/* Hero Section */}
      <header className="relative z-10 max-w-7xl mx-auto px-8 pt-24 pb-24 text-center">
        {/* Radial Glow behind Heading */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-emerald-500/[0.07] blur-[120px] rounded-full pointer-events-none select-none" />
        
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="space-y-4"
        >
          <div className="inline-flex items-center gap-3 px-5 py-1.5 rounded-full border border-white/5 bg-white/[0.02] backdrop-blur-md">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.8)] animate-pulse" />
            <span className="text-[9px] font-mono font-bold uppercase tracking-[0.3em] text-white/40">Sustainability Intelligence v4.0</span>
          </div>
          
          <h1 className="text-5xl lg:text-7xl font-display font-extrabold tracking-tighter leading-[0.9] text-white">
            ECOSPHERE <span className="text-emerald-500 drop-shadow-[0_0_15px_rgba(16,185,129,0.3)]">AI</span>
          </h1>
          
          <p className="text-lg lg:text-xl font-serif italic text-white/60 max-w-2xl mx-auto tracking-tight">
            “Turning Sustainability Into <span className="text-white not-italic font-display font-semibold">Smart Decisions.</span>”
          </p>
          
          <p className="text-sm text-white/30 max-w-xl mx-auto leading-relaxed font-medium">
            An AI-powered sustainability intelligence platform that predicts energy usage, 
            estimates carbon emissions, analyzes water consumption, and optimizes waste efficiency.
          </p>

          <div className="pt-6">
            <button
              onClick={() => setShowModal(true)}
              className="group relative px-10 py-5 bg-gradient-to-br from-emerald-500 to-teal-600 text-black font-mono font-black text-[10px] uppercase tracking-[0.4em] rounded-xl shadow-[0_10px_40px_rgba(16,185,129,0.2)] hover:shadow-[0_15px_50px_rgba(16,185,129,0.4)] hover:scale-105 transition-all duration-500 overflow-hidden"
            >
              <span className="relative z-10 flex items-center gap-4">
                Enter Platform <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
              </span>
              <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-500" />
            </button>
          </div>
        </motion.div>
      </header>

      {/* About Section */}
      <section className="relative z-10 max-w-7xl mx-auto px-8 py-20 border-t border-white/[0.03]">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-display font-bold tracking-tight text-white">Intelligence for a <span className="text-emerald-500">Greener Future.</span></h2>
              <p className="text-white/40 leading-relaxed text-base font-medium">
                EcoSphere AI leverages advanced neural networks to transform raw facility data into actionable environmental strategies.
              </p>
            </div>
            
            <div className="space-y-4">
              {[
                { title: 'Predictive Resource Modeling', desc: 'Anticipate consumption patterns before they happen.' },
                { title: 'AI-Driven Recommendations', desc: 'Actionable protocols tailored to your facility type.' },
                { title: 'Impact Reduction', desc: 'Lower environmental footprint and operational costs simultaneously.' },
              ].map((item, idx) => (
                <div key={idx} className="flex gap-5">
                  <div className="w-10 h-10 rounded-lg bg-white/[0.02] border border-white/[0.05] flex items-center justify-center flex-shrink-0">
                    <ChevronRight className="text-emerald-500" size={18} />
                  </div>
                  <div>
                    <h4 className="text-white font-bold text-sm mb-0.5">{item.title}</h4>
                    <p className="text-white/30 text-xs">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div className="relative aspect-video rounded-[3rem] overflow-hidden border border-white/[0.05] group shadow-2xl">
            <img 
              src="https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=2070" 
              alt="Sustainability" 
              className="w-full h-full object-cover opacity-40 group-hover:scale-105 transition-transform duration-1000"
              referrerPolicy="no-referrer"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-[#020d0a] via-transparent to-transparent" />
            <div className="absolute bottom-6 left-6 right-6 p-6 glass rounded-2xl">
              <p className="text-white/40 font-mono text-[9px] uppercase tracking-widest mb-1">Neural Engine Status</p>
              <p className="text-white font-display text-lg font-bold tracking-tight">Optimizing 4.2M sq. ft. of infrastructure globally.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Key Features Section */}
      <section className="relative z-10 max-w-7xl mx-auto px-8 py-20 border-t border-white/[0.03]">
        <div className="text-center mb-12 space-y-2">
          <h2 className="text-3xl font-display font-bold tracking-tight text-white">Core Capabilities</h2>
          <p className="text-white/20 font-mono text-[9px] uppercase tracking-[0.3em]">Advanced Sustainability Protocols</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, idx) => (
            <div 
              key={idx} 
              className={cn(
                "p-8 glass rounded-[2.5rem] space-y-4 group transition-all duration-500",
                "border-[1.5px] border-white/[0.08] hover:-translate-y-1.5",
                feature.border
              )}
            >
              <div className={cn(
                "w-12 h-12 rounded-xl bg-white/[0.02] border border-white/[0.05] flex items-center justify-center transition-all duration-500 shadow-inner",
                "group-hover:scale-110",
                feature.color
              )}>
                <feature.icon 
                  size={24} 
                  strokeWidth={1.5} 
                  className="transition-all duration-500 group-hover:drop-shadow-[0_0_8px_currentColor]" 
                />
              </div>
              <div className="space-y-1">
                <h4 className="text-lg font-display font-bold text-white group-hover:glow-text-green transition-all duration-500">{feature.title}</h4>
                <p className="text-xs text-white/30 leading-relaxed font-medium">{feature.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works Section */}
      <section className="relative z-10 max-w-7xl mx-auto px-8 py-20 border-t border-white/[0.03]">
        <div className="text-center mb-12 space-y-2">
          <h2 className="text-3xl font-display font-bold tracking-tight text-white">Neural Workflow</h2>
          <p className="text-white/20 font-mono text-[9px] uppercase tracking-[0.3em]">From Data to Impact</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {steps.map((step, idx) => (
            <div key={idx} className="relative space-y-3">
              <div className="text-5xl font-display font-black text-white/[0.02] absolute -top-6 -left-2 select-none">{step.number}</div>
              <div className="relative z-10 space-y-1">
                <h4 className="text-lg font-display font-bold text-white">{step.title}</h4>
                <p className="text-xs text-white/30 leading-relaxed font-medium">{step.desc}</p>
              </div>
              {idx < steps.length - 1 && (
                <div className="hidden lg:block absolute top-1/2 -right-4 w-8 h-[1px] bg-white/10" />
              )}
            </div>
          ))}
        </div>
      </section>

      {/* Who It's For Section */}
      <section className="relative z-10 max-w-7xl mx-auto px-8 py-20 border-t border-white/[0.03]">
        <div className="text-center mb-12 space-y-2">
          <h2 className="text-3xl font-display font-bold tracking-tight text-white">Built for Scale</h2>
          <p className="text-white/20 font-mono text-[9px] uppercase tracking-[0.3em]">Industry-Specific Optimization</p>
        </div>
        
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
          {targets.map((target, idx) => (
            <div key={idx} className="p-8 glass rounded-[2.5rem] text-center space-y-4 group hover:bg-white/[0.03] transition-all duration-500">
              <div className="w-16 h-16 mx-auto rounded-2xl bg-white/[0.02] border border-white/[0.05] flex items-center justify-center text-white/10 group-hover:text-emerald-500 group-hover:scale-110 transition-all duration-500">
                <target.icon size={32} strokeWidth={1} />
              </div>
              <h4 className="text-base font-display font-bold text-white/60 group-hover:text-white transition-colors">{target.type}</h4>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 max-w-7xl mx-auto px-8 py-20 border-t border-white/[0.03] text-center">
        <div className="flex flex-col items-center gap-8">
          <div className="flex items-center gap-4">
            <Leaf className="text-emerald-500" size={24} />
            <span className="text-xl font-display font-bold tracking-tighter">ECOSPHERE AI</span>
          </div>
          <p className="text-white/20 font-mono text-[10px] uppercase tracking-[0.5em]">© 2026 Sustainability Protocol Engine</p>
        </div>
      </footer>

      {/* Entry Modal */}
      <AnimatePresence>
        {showModal && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 md:p-12">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowModal(false)}
              className="absolute inset-0 bg-black/80 backdrop-blur-2xl"
            />
            
            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className="relative w-full max-w-[600px] max-h-[85vh] overflow-y-auto glass rounded-[3rem] md:rounded-[4rem] p-8 md:p-9 space-y-5 md:space-y-6 shadow-[0_40px_100px_rgba(0,0,0,0.8)] border border-white/10 custom-scrollbar"
            >
              <button 
                onClick={() => setShowModal(false)}
                className="absolute top-7 right-7 w-9 h-9 rounded-full bg-white/[0.02] border border-white/[0.05] flex items-center justify-center text-white/20 hover:text-white hover:bg-white/[0.05] transition-all"
              >
                <X size={16} />
              </button>

              <div className="space-y-2">
                <h3 className="text-2xl md:text-3xl font-display font-bold tracking-tight text-white">Launch Dashboard</h3>
                <p className="text-white/30 text-sm leading-relaxed">Configure your facility context to initialize the neural sustainability engine.</p>
              </div>

              <div className="space-y-5">
                <div className="space-y-2">
                  <label className="text-[10px] font-mono font-black text-white/20 uppercase tracking-[0.3em] ml-2">Institution Name</label>
                  <input 
                    type="text" 
                    value={institutionName}
                    onChange={(e) => setInstitutionName(e.target.value)}
                    placeholder="e.g. Stanford Medical Center"
                    className="w-full bg-white/[0.02] border border-white/[0.05] rounded-2xl px-6 py-3.5 text-white placeholder:text-white/10 focus:outline-none focus:border-emerald-500/50 focus:bg-white/[0.04] transition-all"
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-[10px] font-mono font-black text-white/20 uppercase tracking-[0.3em] ml-2">Building Type</label>
                  <div className="grid grid-cols-2 gap-3">
                    {(['Campus', 'Office', 'Residential', 'Hospital'] as BuildingType[]).map((type) => (
                      <button
                        key={type}
                        onClick={() => setSelectedType(type)}
                        className={cn(
                          "px-6 py-2.5 rounded-2xl text-[10px] font-mono font-bold uppercase tracking-widest border transition-all duration-500",
                          selectedType === type
                          ? "bg-emerald-500 text-black border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.3)]"
                          : "bg-white/[0.02] border-white/[0.05] text-white/30 hover:bg-white/[0.05] hover:text-white/60"
                        )}
                      >
                        {type}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div className="flex flex-col gap-1 pt-2">
                <button
                  onClick={() => onLaunch(institutionName, selectedType)}
                  disabled={!institutionName.trim()}
                  className="w-full py-3.5 bg-emerald-500 text-black font-mono font-black text-xs uppercase tracking-[0.4em] rounded-2xl shadow-[0_0_40px_rgba(16,185,129,0.2)] hover:scale-[1.02] active:scale-[0.98] transition-all duration-500 disabled:opacity-20 disabled:hover:scale-100"
                >
                  Launch Dashboard
                </button>
                <button
                  onClick={() => setShowModal(false)}
                  className="w-full py-2 text-white/20 font-mono font-black text-[10px] uppercase tracking-[0.4em] hover:text-white transition-colors"
                >
                  Cancel
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

const Sparkles = ({ size, className }: { size: number, className?: string }) => (
  <svg 
    width={size} 
    height={size} 
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="1.5" 
    strokeLinecap="round" 
    strokeLinejoin="round" 
    className={className}
  >
    <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z" />
    <path d="M5 3v4" />
    <path d="M19 17v4" />
    <path d="M3 5h4" />
    <path d="M17 19h4" />
  </svg>
);
